// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
import 'firebase_options.dart';


 // ignore: non_constant_identifier_names
//  await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPkWe3SmtjpxeeEurhYE5e3xl4O7me5PA',
    appId: '1:87472838349:web:03c2c726d84f20cb71fb84',
    messagingSenderId: '87472838349',
    projectId: 'parkocpk',
    authDomain: 'parkocpk.firebaseapp.com',
    storageBucket: 'parkocpk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeyvNJ2j0Y29ySuE_DhQpNFuyB1duf3k',
    appId: '1:87472838349:android:a804db4db469b85771fb84',
    messagingSenderId: '87472838349',
    projectId: 'parkocpk',
    storageBucket: 'parkocpk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJWDLGgJ5eW29hks99-3XR4Z39jJodEXk',
    appId: '1:87472838349:ios:49a5d5075215fd5271fb84',
    messagingSenderId: '87472838349',
    projectId: 'parkocpk',
    storageBucket: 'parkocpk.appspot.com',
    iosClientId: '87472838349-iikorajm0ltl2aottri3pvkr9vbspqq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJWDLGgJ5eW29hks99-3XR4Z39jJodEXk',
    appId: '1:87472838349:ios:49a5d5075215fd5271fb84',
    messagingSenderId: '87472838349',
    projectId: 'parkocpk',
    storageBucket: 'parkocpk.appspot.com',
    iosClientId: '87472838349-iikorajm0ltl2aottri3pvkr9vbspqq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkoc',
  );
}
